web3j:
  client-address: http://localhost:9545
  http-timeout-seconds: 600
gaslimit: 4700000
daimler:
  contract:
    address: 0x284c5966270565c0d327c67c2d9708966fb83772
---
privatekey: 9a5711d5335f1bf0cf88625438dfb07af79ad0aa7d22fec551818788d67f2a4a
server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:daimler
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  profiles: daimler
---
spring:
  profiles: zf
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:zf
    username: sa
    password: 
    driver-class-name: org.h2.Driver
server:
  port: 8081
privatekey: 733e0a723baab4e243a27c07675263a7f3d834e67aa89dd70864050575aef830
---
spring:
  profiles: car
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:car
    username: sa
    password: 
    driver-class-name: org.h2.Driver
server:
  port: 8082
privatekey: 560c467a75a565e293cb0a3ae3543242e9e8b7c3e9b901643874038e9e5b2b49